#!/usr/bin/env ansible-playbook
- hosts: localhost
  tasks:
    - debug:
        msg: Check we are running in the directory of the script
      failed_when: not ansible_env.PWD.endswith('/dotfiles')

- hosts: localhost
  vars_files:
    - become-password.secret
  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
      homebrew_brewfile_dir: ansible_env.PWD
    - js_mac
