- name: Set fact for dotfiles path
  set_fact:
    # NOTE: Do keep the slash at the end!
    dotfiles_path: "{{ ansible_env.PWD }}/files/dotfiles/"

- name: Find all dotfiles directories
  find:
    paths: "{{ dotfiles_path }}"
    file_type: directory
    recurse: true
    hidden: true
  register: dotfiles_directories

- name: Ensure paths for dotfiles exist
  file:
    path: "~/{{ item.path | replace(dotfiles_path, '') }}"
    state: directory
    mode: 0755
  with_items: "{{ dotfiles_directories.files }}"

- name: Find all dotfiles to be linked
  find:
    paths: "{{ dotfiles_path }}"
    file_type: file
    recurse: true
    hidden: true
  register: dotfiles

- name: Symlink dotfiles
  file:
    src: "{{ item.path }}"
    dest: "~/{{ item.path | replace(dotfiles_path, '') }}"
    state: link
    force: true
  with_items: "{{ dotfiles.files }}"
