windows:
  - name: upgrade
    root: ~/Documents
    layout: tiled
    panes:
      - commands:
          - brew upgrade
          - brew upgrade --cask
          - mas upgrade
          - brew bundle dump -f --mas --file ecosystem/dotfiles/Brewfile
      - commands:
          - gitup -c ecosystem qm suitecrm tblue transact
      - commands:
          - upgrade_vim
      - commands:
          - joplin sync
          - omz update
