- name: Install homebrew packages
  command: brew bundle install -v
  register: brew_output
  # TODO: Add correct condition
  changed_when: brew_output.rc != 0

- name: Omz should be installed and configured
  import_role:
    name: gantsign.oh-my-zsh
  vars:
    oh_my_zsh_theme: romkatv/powerlevel10k
    oh_my_zsh_install: yes
    users:
      - username: "{{ ansible_user_id }}"

- name: Omz plugins should be installed
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item | regex_replace('.*\\/(.*)\\.git', '\\1') }}"
    force: yes
  loop:
    - https://github.com/lukechilds/zsh-nvm.git

# NOTE: Should run before dotfiles.yml so the config file is not overwritten
- name: Set up vim config
  import_tasks: vim.yml

- name: Set up dotfiles
  import_tasks: dotfiles.yml

- name: iTerm custom settings file should be set
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "{{ ansible_env.PWD }}/roles/js_mac/files"
